# Generated by Django 4.1.1 on 2022-09-18 21:14

import bidding.tools
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата старта аукциона')),
                ('ends_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата окончания аукциона')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название предмета')),
                ('image', models.ImageField(default='item_images/default.png', upload_to='item_images', verbose_name='Картинка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('starting_price', models.PositiveIntegerField(default=0, verbose_name='Стартовая цена')),
                ('winning_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Выигрышная цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding.category', verbose_name='Категория')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('previous_owners', models.ManyToManyField(related_name='previous_owners', to=settings.AUTH_USER_MODEL, verbose_name='Бывшие владельцы')),
            ],
            options={
                'verbose_name': 'предмет на ставку',
                'verbose_name_plural': 'Предметы на ставку',
            },
            bases=(bidding.tools.ResizeImageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding.item', verbose_name='Предмет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('bid_placed_at', models.DateTimeField(auto_now=True, verbose_name='Дата ставки')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding.auction', verbose_name='Аукцион')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding.item', verbose_name='Предмет'),
        ),
    ]
