# Generated by Django 4.1.1 on 2022-09-22 21:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'verbose_name': 'аукцион', 'verbose_name_plural': 'Аукционы'},
        ),
        migrations.AlterModelOptions(
            name='bid',
            options={'verbose_name': 'ставка', 'verbose_name_plural': 'Ставки'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'список желаемого', 'verbose_name_plural': 'Список желаемого'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='starting_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='winning_price',
        ),
        migrations.AddField(
            model_name='auction',
            name='starting_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Стартовая цена'),
        ),
        migrations.AddField(
            model_name='auction',
            name='winning_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Выигрышная цена'),
        ),
        migrations.AlterField(
            model_name='item',
            name='previous_owners',
            field=models.ManyToManyField(blank=True, null=True, related_name='previous_owners', to=settings.AUTH_USER_MODEL, verbose_name='Бывшие владельцы'),
        ),
    ]
