# Generated by Django 4.1.1 on 2022-09-26 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bidding', '0008_auction_leader_alter_auction_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='previous_owners',
            field=models.ManyToManyField(blank=True, related_name='previous_owners', to=settings.AUTH_USER_MODEL, verbose_name='Бывшие владельцы'),
        ),
    ]
