# Generated by Django 4.1.1 on 2022-09-26 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bidding', '0009_alter_item_previous_owners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='leader',
        ),
        migrations.AddField(
            model_name='auction',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Завершён?'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Победитель'),
        ),
    ]
