# Generated by Django 4.1.1 on 2022-09-29 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0011_alter_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='starts_at',
        ),
    ]
